---
- name: Install Docker and deploy compose stack
  hosts: web_servers
  become: true

  vars_files:
    - vault/secrets.yml

  vars:
    project_dir: "/home/ssp/monitoring"
    ansible_user: "{{ web_server_user }}"
    ansible_password: "{{ web_server_password }}"
    ansible_become_password: "{{ web_server_password }}"

  tasks:

  # - name: Update apt cache
  #   apt:
  #     update_cache: yes
  #   when: ansible_facts['os_family'] == "Debian"

  # - name: Install required dependencies
  #   apt:
  #     name:
  #       - ca-certificates
  #       - curl
  #       - gnupg
  #     state: present
  #     update_cache: yes

  # - name: Create Docker keyring directory
  #   file:
  #     path: /etc/apt/keyrings
  #     state: directory
  #     mode: "0755"

  # - name: Download Docker GPG key
  #   get_url:
  #     url: https://download.docker.com/linux/ubuntu/gpg
  #     dest: /etc/apt/keyrings/docker.asc
  #     mode: "0644"

  # - name: Add Docker repository
  #   apt_repository:
  #     repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  #     filename: docker
  #     state: present

  # - name: Update apt cache after adding Docker repo
  #   apt:
  #     update_cache: yes

  # - name: Install Docker Engine and Compose v2
  #   apt:
  #     name:
  #       - docker-ce
  #       - docker-ce-cli
  #       - containerd.io
  #       - docker-buildx-plugin
  #       - docker-compose-plugin
  #     state: present

  # - name: Ensure Docker service is started
  #   service:
  #     name: docker
  #     state: started
  #     enabled: true

  - name: Add user to docker group
    user:
      name: "{{ web_server_user }}"
      groups: docker
      append: yes

  - name: Create project directory
    file:
      path: "{{ project_dir }}"
      state: directory
      mode: "0755"

  - name: Copy docker compose file
    copy:
      src: "docker/compose.yml"
      dest: "{{ project_dir }}/docker-compose.yml"

  - name: Copy prometheus file
    copy:
      src: "prometheus.yml"
      dest: "{{ project_dir }}/prometheus.yml"

  - name: Copy alert file
    copy:
      src: "alert.yml"
      dest: "{{ project_dir }}/alert.yml"

  - name: Copy alert manager file
    copy:
      src: "alertManager.yml"
      dest: "{{ project_dir }}/alertManager.yml"

  - name: Add hostnames to /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
      state: present
    loop:
      - "10.180.93.12  suggestion_model"
      - "10.180.93.12  classification_model"
      - "10.180.93.12  content_moderation"
      - "10.180.93.12  rocm_exporter"
      - "10.182.0.210 geo"
      - "10.180.22.114 mongodb-primary"
      - "10.180.22.115 mongodb-secondary"
      - "10.180.22.116 mongodb-arbiter"
      - "10.180.148.197 stoneinscription-backend"

  - name: Tear down existing stack completely
    community.docker.docker_compose_v2:
      project_src: "{{ project_dir }}"
      state: absent
      remove_orphans: true
      remove_volumes: true

  - name: Start Monitoring stack with docker compose
    community.docker.docker_compose_v2:
      project_src: "{{ project_dir }}"
      state: present
      remove_orphans: true